# fly.toml app configuration file generated for fso-pokedex-4235 on 2024-01-01T12:14:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fso-pokedex-4235"
primary_region = "ams"

[env]
  PORT = "5000" # add this where PORT matches the internal_port below

[deploy]
  release_command = "npm run build"
  strategy = "bluegreen"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health/"
  
