# fly.toml app configuration file generated for fso-pokedex-4235 on 2024-01-01T12:14:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fso-pokedex-4235"
primary_region = "ams"

[deploy]
  release_command = "npm run build"
  strategy = "bluegreen"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.20.2"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"
  
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[services]]
  internal_port = 5000
  processes = ["app"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  force_https = true

[[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"
