name: Health Check

on:
  schedule:
    - cron:  '50,52,54,56,58 18 22 2 *'

jobs:

  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://fso-pokedex-4235.fly.dev/